#version: '3.9'
services:
  postgres:
    container_name: delivery_db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=GMT+3'
      - PGTZ=GMT+3'
    ports:
      - '127.0.0.1:5444:5432'
    volumes:
      - delivery_db:/var/lib/postgresql/data
    networks:
      - local

  api:
    container_name: delivery_api
    image: backend_delivery
    build:       # Build the Docker image using the Dockerfile in the current directory
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres  # Ensure that the backend service starts after the database service is up and running
    ports:
      - '127.0.0.1:5000:5000'  # Forward the container's port 4000 to the host machine's port 4000 for accessing the backend service
    environment:
      - DATABASE_URL=${DATABASE_URL}

networks:
  local:
    driver: bridge

volumes:
  delivery_db:
    external: true
      
  
