name: Delpoy on Demand

on:
  workflow_dispatch
    # push:
    #   branches:
    #     - master
    # pull_request:
    #   branches:
    #     - master
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Stop running container
      #   run: docker compose down || true # Остановка контейнеров Docker

      # - name: Remove backend image
      #   run: docker rmi fy_backend:latest || true  # Удаление Docker об

      # - name: Start backend
      #   run: docker compose up -d  # Запуск контейнеров Docker