name: Delpoy on Demand

on:
  workflow_dispatch
    # push:
    #   branches:
    #     - master
    # pull_request:
    #   branches:
    #     - master
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GIT_TOKEN }}  # Используем секрет GIT_TOKEN для аутентификации
          repository: KirillJBee/delivery-back-DevOps
          ref: master
